CC ?= gcc
CFLAGS ?= -O2 -g -Wall -Wextra -pedantic -std=c99

demo: demo.c
	$(CC) $(CFLAGS) -o $@ $<

sum-matrix: sum-matrix.c
	$(CC) $(CFLAGS) -o $@ $<

array-vs-list: array-vs-list.c
	$(CC) $(CFLAGS) -o $@ $<
